env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - jest
rules: {
  "no-use-before-define": "off", # Giving false positive
  "@typescript-eslint/no-use-before-define": ["warn"],
  # Resolve 'children' missing error without setting PropTypes, see https://forhjy.medium.com/react-solution-for-children-is-missing-in-props-validation-eslint-react-prop-types-2e11bc6043c7
  "react/prop-types": ["off"] 
}
